# Flask module configuration
enabled: true
auto_load: true

# Flask server settings
port: 5000
health_check_interval: 30  # seconds
max_restart_attempts: 3

# Security settings
allowed_origins: ["http://localhost:3000"]
cors_enabled: true

# Resource limits
max_requests_per_minute: 600
timeout: 30  # seconds